image: ruby:2.6.3
services:
  - mdillon/postgis:latest

variables:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""

before_script:
  # Use UTF8
  # - export LC_ALL=en_US.UTF-8
  # - export LANG=en_US.UTF-8
  # - export LANGUAGE=en_US.UTF-8

  # Set to UTC
  - eval $(ssh-agent -s)

  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

  # Add new dependencies below
  - apt-get update -y && apt-get install cmake -y

  - gem install bundler --no-document
  - cp test/dummy/config/database.yml.gitlab test/dummy/config/database.yml
  - bundle install --jobs $(nproc) "${FLAGS[@]}"

stages:
  - test

test:
  stage: test
  script:
    - bundle exec rails db:setup RAILS_ENV=test
    - bundle exec rails app:assets:precompile RAILS_ENV=test
    - bundle exec rails test

rubocop:
  stage: test
  script:
    - bundle exec rubocop
