image: ruby:2.4.2
services:
  - mdillon/postgis:latest

variables:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""

before_script:
  # Use UTF8 and UTC
  - export LC_ALL=en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US.UTF-8
  - export TZ='Etc/UTC'
  # Install deploy key from SSH_PRIVATE_KEY variable from gitlab to docker instance.
  # See:
  # https://gitlab.com/<group>/<project>/settings/ci_cd
  # https://stackoverflow.com/questions/25689231/getting-gitlab-ci-to-clone-private-repositories
   - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  # Add new dependencies below
  - apt-get update -y && apt-get install cmake -y
  # Actually do stuff
  - gem install bundler --no-document
  - cp test/dummy/config/database.yml.gitlab test/dummy/config/database.yml
  - bundle install --jobs $(nproc) "${FLAGS[@]}"

stages:
  - test

test:
  stage: test
  script:
    - bundle exec rails db:setup RAILS_ENV=test
    - bundle exec rails app:assets:precompile RAILS_ENV=test
    - bundle exec rails test

rubocop:
  stage: test
  script:
    - bundle exec rubocop
