inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vagrant/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'lib/generators/**/*'
    - 'node_modules/**/*'
    - 'test/dummy/**/*'
    - 'test/dummy/config/**/*'

Metrics:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '[]'
    '%i': '[]'
    '%q': '[]'
    '%Q': '[]'
    '%r': '[]'
    '%s': '[]'
    '%w': '[]'
    '%W': '[]'
    '%x': '[]'

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: true

Layout/LineLength:
  Max: 1000
